### ISSUE TITLE
Iconify Icons with MaterialUI IconButton

### ISSUE THREAD

**Issue by gz** [iconify/iconify#249] opened 2023-08-25 17:03 UTC
I'm using `@iconify/react` in together with material UI version 5.14.4 to implement action buttons in the material-ui data-grid. e.g., the code looks like this where `<Icon ... />` is from iconify-react

```tsx
            <Tooltip title='Inspect View'>
              <IconButton
                size='small'
                href={`/streaming/inspection/?pipeline_id=${descriptor.pipeline_id}&relation=${params.row.relation.name}`}
              >
                <Icon icon='bx:show' fontSize={20} />
              </IconButton>
            </Tooltip>
```

I encountered a bug once I switched the version of iconify to 4.1.1 (from 4.1.0) in chrome based browsers that sometimes the link no longer works (e.g., no navigation to page specified in href happens. This is also the case if onClick is used instead of href to navigate. In this case the onClick handler doesn't get invoked at all. This happens in ~20% of the clicks and only the first time the button gets clicked. The second time works reliably. 

After downgrade to 4.1.0, everything it worked again.

**Comment by cyberalien** [comment] 2023-08-28 09:46
Click event is not handled by icon, so it is an issue somewhere else.

**Comment by jonnylink** [comment] 2023-10-12 15:45
We are also seeing this issue across all icons included in iconify.

**Comment by cyberalien** [comment] 2023-10-16 11:23
I think different behaviour of icons triggers some bug in IconButton component or code it uses.

When displaying typical icon, it is rendered only once and it is done immediately.

When using Iconify icon components, icon is not rendered immediately. It is rendered only after component has mounted (and icon data is available, so often fraction of a second after component was mounted), which is a necessary workaround for SSR hydration issue.

Maybe that difference in rendering is triggering something in IconButton component that prevents events from working.

Solution is to use a different icon component that bundles icon data and renders icons immediately. I recommend Unplugin Icons. If you do want to load icon data dynamically, another solution is to use web component `@iconify-icon/react`, which renders icon in shadowDOM, avoiding whole SSR hydration mess and probably won't trigger this bug.

**Comment by reorx** [comment] 2024-01-05 13:45
Same here, I'm building a rich text editor with tiptap, I put some buttons that have <Icon icon="..." /> in them as toolbar, and when I rapidly click between these buttons, there's about 20% chance that the button does not work. At first I thought it was because of the rerendering or some callbacks that blocks the UI, but after building a minimum example with one toolbar using no icons and the other using Iconify <Icon> component, I can easily compare out that it's the <Icon> that causes the unresponse issue.

**Comment by jonnylink** [comment] 2024-01-06 00:47
@reorx if you use one of the older versions listed above it'll work again. 

Unfortunately the project owner doesn't seem to accept that this is an Iconify bug. 

It's a great resource otherwise.

**Comment by cyberalien** [comment] 2024-01-06 08:20
> Unfortunately the project owner doesn't seem to accept that this is an Iconify bug.

Because it is not. There is no way icon can affect behavior of parent element. It is just impossible. If event listener on parent element does not work, it is an issue of parent element.

It is a bug of a button component.

**Comment by jonnylink** [comment] 2024-01-06 12:25
I could be wrong. I'd have to look into the code, but since this only happens in more recent versions of this package, so it's hard to reason how it'd be a an issue with something else.

**Comment by reorx** [comment] 2024-01-06 12:34
> It is a bug of a button component.

I have used a raw HTML button to reproduce the issue, so at least it's not a bug in the button component in my case.

One thing I forgot to mention is that, at the time the button did not respond to the click, the whole document also did not respond. This conclusion is reached by adding a click listener on `document` or `window`, and it is hard to believe that they have bugs.

I will provide another example with fewer dependencies later.

**Comment by cyberalien** [comment] 2024-01-06 12:39
Try creating a custom icon component that matches Iconify component in behavior. Iconify component cannot render icon until it loads icon data from API, so it initially renders empty `<span />`. To avoid SSR hydration issues, it doesn't do anything until component has mounted, otherwise it might render different content on server and client resulting in content mismatch. Then it loads icon data, which might be instant or it might take some time (async operation). After receiving data, it re-renders component with icon data.

To emulate that, create a component that:
- Renders empty `<span />` initially.
- Waits for component to be mounted.
- Waits few more milliseconds to emulate async loading.
- Renders icon as `<svg />`.

It would closer match to icon component behavior than basic static icon.

**Comment by cyberalien** [comment] 2024-04-28 16:37
Closing this issue.

As posted above, it is not icon component issue. Icon component does not and cannot affect event listeners on parent elements.

**Closed by cyberalien** 2024-04-28 16:37 UTC

**Comment by jonnylink** [comment] 2024-04-28 17:10
It's your right to close this, but the issue is solved by downgrading and locking the version. We're going to be moving on from this library, so I'm not going to dig and find the bug. I don't see any plausible explanation for this appearing only when using newer versions of this library. It's literally the only thing that causes the bug. 

It's a bit odd to take the stance it's impossible without being able to show why when it's clearly this library causing the issue.

**Comment by cyberalien** [comment] 2024-04-28 17:19
Yes, its a weird bug.

However, it is illogical. Also I have not seen any reports of such bug with any other library, only with MaterialUI. So I firmly believe that bug is in MaterialUI.

Why downgrading to older version fixes it? I don't know. Though I do have a suspicion: older version was designed before SSR was common, so it did not account for it and rendered icon immediately when data is available. Therefore, no re-rendering, it is initially rendered as `<svg>`. New version renders `<span>` until component is mounted to avoid SSR issues. Re-rendering of icon could be triggering a bug in Material UI.

**Comment by jonnylink** [comment] 2024-05-09 20:28
Sorry meant to reply. Just wanted to say thanks for those details. What you've said does sound convincing!
