### ISSUE TITLE
Feature Request: Support `noSSR` prop for React offline use

### ISSUE THREAD

**Issue by nghiepit** [iconify/iconify#152] opened 2022-06-19 06:48 UTC
When using Iconify Offline mode in Next.js or Remix.
The `noSSR` prop is necessary to Avoid an excessive DOM size.

For example PageSpeed Insights warning
![image](https://user-images.githubusercontent.com/4768095/174469266-8622bb7b-99a3-4a82-94aa-fe3ab2ad77ec.png)

**Comment by cyberalien** [comment] 2022-06-19 11:51
Unfortunately SSR has been a major pain.

Solution is to switch to web component `@iconify-icon/react`. It is the same as `@iconify/react`, but uses web component that is rendered only in browser, so it works great with SSR.

Usage example with Next.js: https://github.com/iconify/iconify/blob/next/iconify-icon-demo/nextjs-demo/pages/index.js

**Comment by nghiepit** [comment] 2022-06-19 15:25
Tks @cyberalien. I never knew about `@iconify-icon/react` before. I will try

**Comment by cyberalien** [comment] 2022-06-19 15:29
It is new, I haven't even announced it yet and if you'll look at readme file, it still shows instructions for `@iconify/react` :) 

However, it can be considered stable. It is a wrapper for `iconify-icon` web component, which shares almost all code with other components, so code has been tested and I'm already using that web component in production on my websites.

**Comment by nghiepit** [comment] 2022-06-23 18:20
I'm trying to install `@iconify-icon/react` but Typescript not working.

![image](https://user-images.githubusercontent.com/4768095/175367828-dac10145-714f-40d3-9e04-08114b5034ac.png)

**Comment by cyberalien** [comment] 2022-06-23 18:30
That's a strange error. Can you try this and tell me if it helps?

Open `node_modules/@iconify-icon/react/dist/iconify.d.ts`, find this code:

```ts
interface IconifyIconProps extends React.HTMLProps<HTMLElement>, IconifyIconProperties {
    rotate?: string | number;
}
```

and replace with this:
```ts
interface IconifyIconProps extends Partial<React.HTMLProps<HTMLElement>>, IconifyIconProperties {
    rotate?: string | number;
}
```

**Comment by nghiepit** [comment] 2022-06-23 19:30
>interface IconifyIconProps extends Partial<React.HTMLProps<HTMLElement>>, IconifyIconProperties {
    rotate?: string | number;
}

It doesn't work.
I found the problem, the `IconifyIconProperties` has no exported member `iconify-icon`.

**Comment by cyberalien** [comment] 2022-06-23 21:11
Thanks a lot! That was indeed the problem. It was caused by small configuration issue, which caused bundler to generate incomplete types.

It is after midnight for me, so I'll re-check it again in the morning and will publish an update.

**Comment by cyberalien** [comment] 2022-06-24 06:32
Fixed in version 0.0.2 of React component.

**Comment by nghiepit** [comment] 2022-06-25 03:23
@cyberalien `@iconify-icon/react` no longer support `fontSize` prop.
```tsx
import {Icon} from '@iconify-icon/react';
 <Icon icon={StartIcon} fontSize={16} />
```
>  Property 'fontSize' does not exist on type 'IntrinsicAttributes & Pick<IconifyI

**Comment by cyberalien** [comment] 2022-06-25 05:59
There is no such property and never was. It is part of `style` property: `<Icon icon={StartIcon} style{{fontSize: '16px'}} />`

**Comment by nghiepit** [comment] 2022-06-29 18:32
> iconify-icon { display: inline-block; min-width: 1em; height: 1em; }

Cool, it works with `font-size`. Another question, In the future `@iconify-icon/react` is still supported `width/height` props?
```tsx
<Icon width={20} />
// or
<Icon style={{fontSize: 20}} />
```

**Comment by cyberalien** [comment] 2022-06-29 18:39
It does support those properties.

However, if mixing it with css above, it might cause problems. For example, if you use `<Icon height="24" />`, assuming icon is square (almost all icons are), it will result in 24x24 icon rendered in shadow DOM. However, `iconify-icon` element will still have 1em height and at least 1em width (because of `min-width` instead of `width`). Overflow is visible, so icon will render nicely, but icon's bounding box will be different. So if you want to use code above to fix blinking, you need to use font-size to change icon size.

**Comment by cyberalien** [comment] 2022-09-08 06:45
Published stable version of web component. Closing this issue.

**Closed by cyberalien** 2022-09-08 06:45 UTC
