### ISSUE TITLE
Hey I found an Issue !!

### ISSUE THREAD

**Issue by theutkarshdev** [iconify/iconify#286] opened 2024-02-29 05:26 UTC
**@IHIutch @cyberalien @snake-poison @nghiepdev** 

I found that Global search is not working on your live application https://icon-sets.iconify.design. I am a software developer, doing any help or contribution in this, I will be very happy.

<img width="960" alt="image"  src="https://github.com/iconify/iconify/assets/131646621/d67477d0-10df-42ed-94c5-aa8595bcea83">

**Comment by cyberalien** [comment] 2024-02-29 07:11
Why are you pinging so many people? Please don't ever do that.

Working fine. I've just tested servers, they are currently all up and running, so maybe there was a small downtime.

If you are still experiencing that issue, could be an extension in browser blocking stuff.

**Comment by cyberalien** [comment] 2024-02-29 08:35
Did more tests to see if I can recreate it - can't recreate.

Unfortunately screenshot is not enough to go on. If its an API server issue, you should see network error in network tab of browser's developer tools. If it is an error in code, you should see error in browser console.

Closing issue because cannot reproduce it. If you are still experiencing same issue, please open browser console and check for errors.

**Closed by cyberalien** 2024-02-29 08:35 UTC
