### ISSUE TITLE
Iconify for vue2 creates a new vue instance when using it with Nuxt

### ISSUE THREAD

**Issue by rafael-lua** [iconify/iconify#75] opened 2021-07-09 23:54 UTC
This causes my console to be spawn with "$attrs is readonly" type of errors (related [stackoverflow](https://stackoverflow.com/questions/49585845/attrs-is-readonly-listeners-is-readonly-avoid-mutating-a-prop-directly)))

Here is the console without using iconify at all:
![console1](https://user-images.githubusercontent.com/54607854/125145125-9fa68880-e0f6-11eb-9220-c4b420f92348.PNG)

Now, in a component, I import iconify:
```vue
<template>
  <div>
    <Icon icon="mdi:at" width="32" height="32" />
  </div>
</template>

<script>
import { Icon } from '@iconify/vue2'

export default {
  name: 'ComponentName',
  components: {
    Icon,
  },
}
</script>
```

And this is the console output:

![console2](https://user-images.githubusercontent.com/54607854/125145338-35421800-e0f7-11eb-9c5c-e93d50eeb6b3.PNG)

What can I do to solve this conflict and stop the multiple instances from happening? 

Nuxt version is: ^2.15.7
Iconify 2: ^1.0.0-beta.1

**Comment by cyberalien** [comment] 2021-07-10 07:23
Thanks a lot for reporting this! I'll debug it.

**Comment by cyberalien** [comment] 2021-07-10 08:24
Debugged it, there are definitely some weird things happening. Component is not supposed to include Vue instance, but it does and there are few other bugs.

**Comment by cyberalien** [comment] 2021-07-10 09:29
Actually, component does not include second Vue instance. It correctly imports it as external dependency. Component is not the issue, Nuxt is the one including it second time for some reason.

Why it does that? I don't know. After debugging it for 2 hours, I have more questions than answers.

Vue 2 component is pretty much identical to Vue 3, React and Svelte components. Even build process of those components is identical. Nuxt is not available yet for Vue 3, but for Sapper/SvelteKit and Next.js components have no issues with server side rendering.

I will continue debugging that issue when I'll have more time, but for now for server side rendering I recommend switching from Vue 2 component to SVG framework.

There are 2 ways to use SVG framework with Nuxt: as plugin or as remote script.

To use it as plugin, install `@iconify/iconify` add this to `nuxt.config.js`:
```js
plugins: ['@/node_modules/@iconify/iconify/dist/iconify.min.js'],
```
To use it as remote script, add it to head section of `nuxt.config.js` (added script at the end of section):
```js
	head: {
		title: 'nuxt2-demo',
		htmlAttrs: {
			lang: 'en',
		},
		meta: [
			{ charset: 'utf-8' },
			{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
			{ hid: 'description', name: 'description', content: '' },
			{ name: 'format-detection', content: 'telephone=no' },
		],
		link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
		script: [
			{ src: 'https://code.iconify.design/2/2.0.3/iconify.min.js', body: true },
		],
	},
```

Then in templates use span with icon name: `<span class="iconify" data-icon="logos:nuxt-icon" />`

**Comment by cyberalien** [comment] 2021-08-19 09:18
So I did more debugging, as far as I can tell, problem is in inability to mess with rendering engine, so Nuxt had to use some hacks to do its thing. Vue 2 was never designed with possibility server side rendering. Nothing can be done for Vue 2, it is just how Vue 2 and Nuxt work.

Good news is looks like issue is fixed in Vue 3. Vue 3 was designed differently and looks like it is possible to do proper server side rendering.

**Closed** 2021-08-19 11:22 UTC
